# Generated by Django 6.0.6 on 2026-06-28 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0002_trip_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='day',
            name='day_number',
        ),
        migrations.AddField(
            model_name='day',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
