# Generated by Django 6.0.6 on 2026-06-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0003_alter_day_options_remove_day_day_number_day_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
