# Generated by Django 6.0.6 on 2026-07-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0004_day_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
