# Generated by Django 6.0.6 on 2026-07-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0005_day_comment_waypoint_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='waypoint',
            name='is_refuel',
            field=models.BooleanField(default=False),
        ),
    ]
